// Initial migration - Create all tables
export async function up(db: any) {
  // This would be generated by Prisma migrate
  // prisma migrate dev --name init
}

export async function down(db: any) {
  // Rollback logic
}
